# Global properties
command=~/.config/i3/scripts/$BLOCK_NAME
separator_block_width=15
markup=none
separator=false

[mediaplayer]
label= : 
instance=spotify
interval=3
color=#a9b665

[microphone]
interval=2
color=#d3869b

[volume]
label=墳 : 
interval=5
color=#d8a657

[bandwidth]
interval=5
color=#7daea3
label= : 

[battery]
label= : 
interval=5
color=#d8a657

[date]
command=date '+%a %b-%d %H:%M'
interval=5
label= : 
color=#a89984

# Gruvbox Material Dark
# orange #e78a4e | red #ea6962 | green #a9b665 | yellow #d8a657
# blue #7daea3 | purple #d3869b | aqua #89b482 | fg2 #a89984 | dim #928374